Reworked install/uninstall logic. Added tmux jobs manager. Broke out functions into seperate files for readability.

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.3.6 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -33,6 +33,7 @@ dotfiles_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -57,6 +58,7 @@ dotfiles_install_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -85,6 +87,7 @@ dotfiles_backup_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -106,6 +109,7 @@ dotfiles_uninstall_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "Options:"
 
     # :command.usage_flags
@@ -157,6 +161,8 @@ normalize_input() {
 
 # :command.inspect_args
 inspect_args() {
+  local k
+
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
@@ -165,15 +171,6 @@ inspect_args() {
     done
   else
     echo args: none
-  fi
-
-  if ((${#other_args[@]})); then
-    echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
-    done
   fi
 
   if ((${#deps[@]})); then
@@ -216,37 +213,35 @@ dotfiles_install_command() {
 
   fi
 
-  # reload fonts
-  # fc-cache -fv
-  # starship preset nerd-font-symbols -o ~/.config/starship.toml
-
-  # prevent . and .. from being added to the array
-  GLOBIGNORE=.:..;
-
-  # create an array with the full path to all dotfiles in the dotfile repo
-  myDotfilesFullPath=(~/.config/dotfiles/$platform/homedir/.*)
-
-  # get the filename of the dotfile to be used for symlinking
-  myDotfilesShortPath=( "${myDotfilesFullPath[@]##*/}" )
-
-  unset GLOBIGNORE
-  echo "${myDotfilesShortPath[@]}"
+  homedir=~/.config/dotfiles/$platform/homedir
 
   if test -f ~/.dotfilelock; then
 
-      # Install/reinstall dotfiles
-      for file in "${myDotfilesShortPath[@]}"; do
-          if [ -L ~/$file ] ; then
+      # Recursively symlink individual files from homedir
+      while IFS= read -r -d '' file; do
+          # Get the path relative to homedir (e.g. .fonts/SomeFont.ttf, .local/bin/tjobs)
+          relpath="${file#$homedir/}"
 
-              echo removing old symlink for "$file"
-              rm ~/$file
+          # Create the parent directory in ~ if it doesn't exist
+          mkdir -p ~/$(dirname "$relpath")
+
+          # Remove old symlink if present
+          if [ -L ~/"$relpath" ]; then
+              echo "removing old symlink for $relpath"
+              rm ~/"$relpath"
           fi
 
-          echo symlinking "$file"
-          ln -s ~/.config/dotfiles/$platform/homedir/$file ~/$file
+          echo "symlinking $relpath"
+          ln -s "$file" ~/"$relpath"
 
-      done
-      unset file
+      done < <(find "$homedir" -type f -print0)
+
+      # Rebuild font cache if .fonts were installed
+      if [ -d "$homedir/.fonts" ]; then
+          echo "rebuilding font cache"
+          fc-cache -fv
+      fi
+
   fi
 
   echo done!
@@ -281,24 +276,20 @@ dotfiles_uninstall_command() {
 
   platform=${args[--platform]}
 
-  myDotfilesFullPath=(~/.config/dotfiles/$platform/homedir/.*)
-  myDotfilesShortPath=( "${myDotfilesFullPath[@]##*/}" )
-
-  echo "${myDotfilesShortPath[@]}"
+  homedir=~/.config/dotfiles/$platform/homedir
 
   if test -f ~/.dotfilelock; then
 
-      # Install/reinstall dotfiles
-      for file in "${myDotfilesShortPath[@]}"; do
-          if [ -L ~/$file ] ; then
+      # Remove symlinks for all managed files
+      while IFS= read -r -d '' file; do
+          relpath="${file#$homedir/}"
 
-              echo removing old symlink for "$file"
-              rm ~/$file
-
+          if [ -L ~/"$relpath" ]; then
+              echo "removing symlink for $relpath"
+              rm ~/"$relpath"
           fi
-      done
 
-      unset file
+      done < <(find "$homedir" -type f -print0)
 
   else
       echo "Warning! No lockfile was found. Preventing accidental deletion"
@@ -310,6 +301,8 @@ dotfiles_uninstall_command() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -397,6 +390,8 @@ parse_requirements() {
 
 # :command.parse_requirements
 dotfiles_install_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -467,6 +462,8 @@ dotfiles_install_parse_requirements() {
 
 # :command.parse_requirements
 dotfiles_backup_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -512,6 +509,8 @@ dotfiles_backup_parse_requirements() {
 
 # :command.parse_requirements
 dotfiles_uninstall_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -582,19 +581,20 @@ dotfiles_uninstall_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.2.0"
-  long_usage=''
+  declare -g version="0.2.0"
   set -e
 
 }
 
 # :command.run
 run() {
+  # :command.globals
+  declare -g long_usage=''
   declare -g -A args=()
   declare -g -A deps=()
-  declare -g -a other_args=()
   declare -g -a env_var_names=()
   declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
@@ -605,5 +605,9 @@ run() {
   esac
 }
 
-initialize
-run "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
+  initialize
+  run "${command_line_args[@]}"
+fi
